### ISSUE TITLE
Does it a deepfool or universal adversarial perturbations?

### ISSUE THREAD

**Issue by DAJINZI01** [qilong-zhang/Pytorch_Universal-adversarial-perturbation#1]
I completely look your code in universal_pert.py, and I find that there is nothing about with the UAP.

**Comment by qilong-zhang** [comment]
Hi @DAJINZI01, Universal Adversarial Perturbation (UAP) is based on the Deepfool algorithm, i.e., It iterative craft single perturbation on 10,000 images. So the resultant perturbation is a universal adversarial perturbation. 
You can check the detail in their paper.

**Comment by DAJINZI01** [comment]
Based on what you said, I can user another algorithm, i.e., I-FGSM, MI-FGSM, generate "single" perturbation(that is accumulate the noise based each iteration to a total noise). Is it right?

**Comment by qilong-zhang** [comment]
The official code is based on Deepfool, but you can also use any other algorithm to craft your UAP.
