### ISSUE TITLE
Attention before using!!!

### ISSUE THREAD

**Issue by winterwindwang** [qilong-zhang/Pytorch_Universal-adversarial-perturbation#2]
Firstly, modify the theta to 0.2 in universal_pert.py, otherwise, the algorithm will fall into an endless loop (the default setting set the target fooling to 98%).
Secondly, assign the parameters "epsilon" the 47-th line in search.py to xi, like
v = universal_perturbation(X, val_loader, net, xi=epsilon)

**Comment by qilong-zhang** [comment]
Hi @winterwindwang, thank you very much for pointing out these bugs, which may have been caused by an oversight in my previous upload. I have fixed them, thanks again!
