### ISSUE TITLE
The location of Normalization is confusing

### ISSUE THREAD

**Issue by Huang-yihao** [qilong-zhang/Pytorch_Universal-adversarial-perturbation#3]
I wonder why put normalization in line 20 instead of simply putting it to the last of transform (the location is shown in the green box)?
The result becomes wrong when I put the normalization into transform. It really confuses me.
Could you please answer the question? Thanks very much!

![image](https://user-images.githubusercontent.com/16575311/172013621-039bf4da-543b-4bbf-9ca9-fdc02dfced99.png)

**Comment by qilong-zhang** [comment]
@hyhchaos, it is necessary to put `Normalize` to line 20. Note that if you put it to line 26, input x is no longer in [0,1].

**Comment by Huang-yihao** [comment]
Thanks for your answer!
