### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by shuiminmo** [qilong-zhang/Pytorch_Universal-adversarial-perturbation#5]
Can you post the Baidu network disk link of the training set （already selected 10 images per category）? The original data training set is too large. Thank you very much

**Comment by qilong-zhang** [comment]
Hi @shuiminmo, I'm sorry that the link to the dataset seems to have failed due to the length of time that has passed, but you might consider using `os.walk()` to make the dataset.

**Comment by shuiminmo** [comment]
thank you
